require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 2.6.0
  Exclude:
    - 'debug.rb'
    - 'dev/**/*'

# Allow a longer module
Metrics/ModuleLength:
  Max: 120

# Allow `Marshal.load`, since we want to get the Ruby object from cache
# We assume trusted source for all caching operations
Security/MarshalLoad:
  Enabled: false

# Allow non standard spec file name 
RSpec/FilePath:
  Enabled: false

# Alerts by this cop are irrelevant
RSpec/Rails:
  Enabled: false
