require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop: rentacop.yml

AllCops:
  TargetRubyVersion: 2.6.0
  Exclude:
    - 'debug.rb'
    - 'dev/**/*'

# Allow a longer module
Metrics/ModuleLength:
  Max: 120

# Allow `Marshal.load`, since we want to get the Ruby object from cache
# We assume trusted source for all caching operations
Security/MarshalLoad:
  Enabled: false

# Allow longer examples
RSpec/ExampleLength:
  Max: 8

# Allow deeper nested groups
RSpec/NestedGroups:
  Max: 4

# Prefer `receive` over `have_received`
RSpec/MessageSpies:
  EnforcedStyle: receive

# Allow multiple expectations per block
RSpec/MultipleExpectations:
  Max: 3

# Allow `expect` in `before`, as it is used to ensure the state
RSpec/ExpectInHook:
  Enabled: false

# Allow non standard spec file name 
RSpec/FilePath:
  Enabled: false

# Allow stubbing methods of the subject
RSpec/SubjectStub:
  Enabled: false

# Allow using `subject` explicitly
RSpec/NamedSubject:
  Enabled: false
