language: ruby

rvm:
- "2.3"
- "2.4"
- "2.5"
- "2.6"
# - "2.7"  # Failing for now, due to github.com/httprb/http/issues/582

before_install:
- gem install bundler

script:
- bundle exec rspec
